import { useState } from "react";
import Head from "next/head";
import Link from "next/link";

import { Dropzone, FileMosaic } from "@dropzone-ui/react";
import NavBar from "~/Components/NavBar";

import { MdOutlineGpsFixed } from 'react-icons/md'

import { api } from "~/utils/api";

import { Map, Marker } from "pigeon-maps";
import { getAuth, buildClerkProps } from "@clerk/nextjs/server";
import { GetServerSideProps } from "next";

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { userId } = getAuth(ctx.req);
 
  if (!userId) {
    // handle user is not logged in.
  }
 
  // Load any data your application needs for the page using the userId
  return { props: { ...buildClerkProps(ctx.req), userId } };
};

export default function Home(props: any) {
  const hello = api.post.hello.useQuery({ text: "from tRPC" })
  const [files, setFiles] = useState<Array<any>>([])
  const [location, setLocation] = useState<[number, number] | null>([19.639484,-158.311505])
  const updateFiles = (incommingFiles: any) => {
    setFiles(incommingFiles);
  };

  function getLocation() {
    const returnPosition = (position: any) => {
      setLocation([position.coords.latitude, position.coords.longitude])
    }
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(returnPosition)
    }
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar userId={props.userId}/>
      <div style={{ backgroundImage: 'url(https://www.hpu.edu/cncs/cmdr/img/dfg.jpg)', backgroundAttachment: 'fixed', backgroundSize: 'contain' }}>
        <div className="lg:mx-[16rem] xl:mx-[28rem] py-[4rem] bg-white">
          <h1 className="text-6xl text-center py-[2rem] text-primary">Report Marine Debris</h1>
          <form className="px-[5rem]">
            <div className="grid grid-cols-1 xl:grid-cols-12 gap-4">
              <h2 className="text-4xl xl:col-span-12">Contact Info</h2>
              <div className="form-control xl:col-span-6 w-full">
                <label className="label">
                  <span className="label-text">What is your first name?</span>
                  <span className="label-text-alt text-red-500">Required *</span>
                </label>
                <input type="text" placeholder="Type here" className="input input-primary input-bordered w-full" />
              </div>
              <div className="form-control xl:col-span-6 w-full">
                <label className="label">
                  <span className="label-text">What is your last name?</span>
                  <span className="label-text-alt text-red-500">Required *</span>
                </label>
                <input type="text" placeholder="Type here" className="input input-primary input-bordered w-full" />
              </div>
              <div className="form-control xl:col-span-4 w-full">
                <label className="label">
                  <span className="label-text">Email</span>
                  <span className="label-text-alt text-red-500">Required *</span>
                </label>
                <input type="text" placeholder="Type here" className="input input-primary input-bordered w-full" />
              </div>
              <div className="form-control xl:col-span-4 w-full">
                <label className="label">
                  <span className="label-text">Confirm your email</span>
                  <span className="label-text-alt text-red-500">Required *</span>
                </label>
                <input type="text" placeholder="Type here" className="input input-primary input-bordered w-full" />
              </div>
              <div className="form-control xl:col-span-4 w-full">
                <label className="label">
                  <span className="label-text">Phone Number</span>
                  <span className="label-text-alt text-red-500">Required *</span>
                </label>
                <input type="text" placeholder="Type here" className="input input-primary input-bordered w-full" />
              </div>
              <div className="form-control xl:col-span-12 w-full">
                <label className="label">
                  <span className="label-text">Mailing Address</span>
                  <span className="label-text-alt text-red-500"></span>
                </label>
                <input type="text" placeholder="Type here" className="input input-primary input-bordered w-full" />
              </div>
              <div className="form-control xl:col-span-4 w-full">
                <label className="label">
                  <span className="label-text">City</span>
                  <span className="label-text-alt text-red-500"></span>
                </label>
                <input type="text" placeholder="Type here" className="input input-primary input-bordered w-full" />
              </div>
              <div className="form-control xl:col-span-4 w-full max-w-xs">
                <label className="label">
                  <span className="label-text">State</span>
                  <span className="label-text-alt text-red-500"></span>
                </label>
                <select className="select select-primary select-bordered">
                  <option disabled selected>Pick one</option>
                  <option>Star Wars</option>
                  <option>Harry Potter</option>
                  <option>Lord of the Rings</option>
                  <option>Planet of the Apes</option>
                  <option>Star Trek</option>
                </select>
              </div>
              <div className="form-control xl:col-span-4 w-full">
                <label className="label">
                  <span className="label-text">Zip Code</span>
                  <span className="label-text-alt text-red-500"></span>
                </label>
                <input type="text" placeholder="Type here" className="input input-primary input-bordered w-full" />
              </div>
            </div>
            <div className="grid grid-cols-1 xl:grid-cols-12 gap-4 mt-[4rem]">
              <h2 className="text-4xl xl:col-span-12">Marine Debris</h2>
              <fieldset className="xl:col-span-12">
                <legend className="text-lg">I found / located the following</legend>
                <div className="grid xl:grid-cols-4 gap-4">
                  <div>
                    <label className="label cursor-pointer">
                      <span className="label-text">A mass of netting and/or fishing gear</span>
                      <input type="checkbox" className="checkbox checkbox-primary" id="last 6 months" name="new" value="last 6 months" />
                    </label>
                  </div>
                  <div>
                    <label className="label cursor-pointer">
                      <span className="label-text">An abandoned/derelict boat</span>
                      <input type="checkbox" className="checkbox checkbox-primary" id="last 6 months" name="new" value="last 6 months" />
                    </label>
                  </div>
                </div>
              </fieldset>
              <div className="xl:col-span-12">
                <label>
                  <span className="text-lg">
                    ENTER MY OWN DESCRIPTION OF THE TYPE OF DEBRIS FOUND AND WHAT
                    IT WOULD TAKE TO REMOVE IT (for example, a large section of a dock
                    or a shipping container requiring a crane to remove, a wooden beam 10'
                    long that would require 3-4 people to lift, etc.)
                  </span>
                  <textarea className="textarea textarea-primary w-full h-[10rem]" placeholder="Bio"></textarea>
                </label>
              </div>
              <div className="xl:col-span-6">
                <div className="form-control w-full">
                  <label className="label">
                    <span className="label-text">Did you find a container, a drum, or cylinder? If yes,<br /> how full is it?</span>
                    <span className="label-text-alt"></span>
                  </label>
                  <select className="select select-primary w-full">
                    <option disabled selected>Pick one</option>
                    <option>Game of Thrones</option>
                    <option>Lost</option>
                    <option>Breaking Bad</option>
                    <option>Walking Dead</option>
                  </select>
                </div>
              </div>
              <div className="xl:col-span-6">
                <div className="form-control w-full">
                  <label className="label">
                    <span className="label-text">Did you find a boat? If yes, do you want to claim it for personal use?</span>
                    <span className="label-text-alt text-red-500">Required *</span>
                  </label>
                  <select className="select select-primary w-full">
                    <option disabled selected>Pick one</option>
                    <option>Game of Thrones</option>
                    <option>Lost</option>
                    <option>Breaking Bad</option>
                    <option>Walking Dead</option>
                  </select>
                </div>
              </div>
              <div className="xl:col-span-12">
                <div className="form-control w-full">
                  <label className="label">
                    <span className="label-text">
                      On a scale of one to ten (one represents no marine growth and ten represents
                      significant marine life covering all submerged surfaces) how much biofouling
                      is on the item you found?
                    </span>
                    <span className="label-text-alt text-red-500">Required *</span>
                  </label>
                  <select className="select select-primary w-full">
                    <option disabled selected>Pick one</option>
                    <option>Game of Thrones</option>
                    <option>Lost</option>
                    <option>Breaking Bad</option>
                    <option>Walking Dead</option>
                  </select>
                </div>
              </div>
              <div className="xl:col-span-6">
                <div className="form-control w-full">
                  <label className="label">
                    <span className="label-text">
                      THIS DEBRIS IS LOCATED
                    </span>
                    <span className="label-text-alt text-red-500">Required *</span>
                  </label>
                  <select className="select select-primary w-full">
                    <option disabled selected>Pick one</option>
                    <option>Game of Thrones</option>
                    <option>Lost</option>
                    <option>Breaking Bad</option>
                    <option>Walking Dead</option>
                  </select>
                </div>
              </div>
              <div className="xl:col-span-6">
                <div className="form-control w-full">
                  <label className="label">
                    <span className="label-text">
                      If on land or in the nearshore waters - indicate which island
                    </span>
                    <span className="label-text-alt text-red-500">Required *</span>
                  </label>
                  <select className="select select-primary w-full">
                    <option disabled selected>Pick one</option>
                    <option>Game of Thrones</option>
                    <option>Lost</option>
                    <option>Breaking Bad</option>
                    <option>Walking Dead</option>
                  </select>
                </div>
              </div>
              <div className="form-control xl:col-span-6 w-full">
                <label className="label">
                  <span className="label-text">Nearest town, street address,<br /> nearby landmarks</span>
                  <span className="label-text-alt text-red-500">Required *</span>
                </label>
                <div className="flex">
                  <input type="text" placeholder="Type here" className="input input-primary input-bordered w-full" />
                </div>
              </div>
              <div className="form-control xl:col-span-6 w-full">
                <label className="label">
                  <span className="label-text">Where is the debris situated in relation to the landmark you provided (i.e. 200 feet north, etc.)</span>
                  <span className="label-text-alt text-red-500"></span>
                </label>
                <input type="text" placeholder="Type here" className="input input-primary input-bordered w-full" />
              </div>
              <div className="xl:col-span-12">
                <div className="form-control w-full">
                  <label className="label">
                    <span className="label-text">
                      THE DEBRIS IS BEST DESCRIBED AS:
                    </span>
                    <span className="label-text-alt text-red-500">Required *</span>
                  </label>
                  <select className="select select-primary w-full">
                    <option disabled selected>Pick one</option>
                    <option>Game of Thrones</option>
                    <option>Lost</option>
                    <option>Breaking Bad</option>
                    <option>Walking Dead</option>
                  </select>
                </div>
              </div>
              <div className="xl:col-span-12">
                <label>
                  <span className="text-lg">
                    ENTER MY OWN DESCRIPTION
                  </span>
                  <textarea className="textarea textarea-primary w-full h-[10rem]" placeholder="Bio"></textarea>
                </label>
              </div>
              <div className="xl:col-span-12">
                <label>
                  <span className="text-lg">
                    IF YOU CAN TAKE A PHOTOGRAPH, PLEASE TURN ON THE LOCATOR/GPS OF YOUR DEVICE, TAKE THE PICTURE AND ATTACH IT
                  </span>
                  <Dropzone onChange={updateFiles} maxFiles={8} maxFileSize={31460000} accept="image/*" value={files}>
                    {files.map((file) => (
                      <FileMosaic {...file} preview />
                    ))}
                  </Dropzone>
                </label>
              </div>
              <div className="xl:col-span-12">
              <button onClick={getLocation} type="button" className="btn w-full btn-primary">Current Location <MdOutlineGpsFixed /></button>
              <Map height={300} defaultCenter={[19.639484,-158.311505]} center={location !== null ? location : [19.639484,-158.311505]} defaultZoom={6}>
                {location !== null && <Marker width={50} anchor={location} color={`hsl(${20 % 360}deg 39% 70%)`}/>}
              </Map>
              </div>
              <div className="xl:col-span-12">
                <button className="btn btn-primary float-right">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </>
  );
}
