import NavBar from "~/Components/NavBar";

import Head from "next/head";


export default function Signin() {
  return (
    <>
      <Head>
        <title>HPU Center for Marine Debris Research</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar userId={null} />
      <div className="flex justify-center pt-[20rem]">
        
      </div>
    </>
  )
}